修复 kuwo 音源 && 音乐云盘上传
1715173329/UnblockNeteaseMusic pull request #1207
Opened 2023-08-16 20:41 UTC by Inkarro

将搜索API替换成客户端的搜索API

2023-08-16 23:19 UTC, Inkarro commented
顺带修了下 音乐云盘上传#1201 ，用了排除法定位到了是这里的问题。

2023-08-17 04:00 UTC, 1715173329 requested changes

2023-08-17 04:00 UTC, 1715173329 commented on src/provider/kuwo.js
>  	duration: song.duration * 1000,
```suggestion
	duration: song.DURATION * 1000,
```

2023-08-17 04:00 UTC, 1715173329 commented on src/provider/kuwo.js
> +	album: { id: song.ALBUMID, name: song.album },
```suggestion
	album: { id: song.ALBUMID, name: song.ALBUM },
```

2023-08-17 04:00 UTC, 1715173329 commented on src/provider/kuwo.js
> +	const url = `http://search.kuwo.cn/r.s?user=114514&android_id=114514&prod=kwplayer_ar_10.5.5.0&corp=kuwo&newver=3&vipver=10.5.5.0&source=kwplayer_ar_10.5.5.0_40.apk&p2p=1&q36=f2ce3c2ef68ddfd1b2bea7e
```suggestion
	const url =
		'http://search.kuwo.cn/r.s?&correct=1&stype=comprehensive&encoding=utf8' +
		'&rformat=json&mobi=1&show_copyright_off=1&searchapi=6&all=' +
		keyword;
```

这一串太长，去掉一些无用的参数并换行。

2023-08-17 04:00 UTC, 1715173329 commented on src/hook.js
>  				if (req.url.includes('stream')) return; // look living eapi can not be decrypted
```suggestion
				if (
					req.url.includes('stream') ||
					req.url.includes('/eapi/cloud/upload/check')
				)
					return; // look living/cloudupload eapi can not be decrypted
				req.headers['Accept-Encoding'] = 'gzip, deflate'; // https://blog.csdn.net/u013022222/article/details/51707352
```

目前也不需要处理云盘上传，就和直播一样直接 return 就行

2023-08-17 04:02 UTC, 1715173329 commented on src/provider/kuwo.js
> +	const url = `http://search.kuwo.cn/r.s?user=114514&android_id=114514&prod=kwplayer_ar_10.5.5.0&corp=kuwo&newver=3&vipver=10.5.5.0&source=kwplayer_ar_10.5.5.0_40.apk&p2p=1&q36=f2ce3c2ef68ddfd1b2bea7e
另外这个 api 和之前注释的那个（L19-L44）只有参数上的差别，可以把那个删掉。

2023-08-17 13:43 UTC, 1715173329 approved these changes
LGTM - Thanks!

2023-08-17 13:46 UTC, merged

2023-08-20 12:55 UTC, SpeedPartner commented
牛啤~!