添加node-windows模块，将nodejs注册成Windows服务
1715173329/UnblockNeteaseMusic pull request #128
Opened 2021-08-31 16:22 UTC by whosydd

无意中看到`node-windows`这个包，感觉这个项目直接注册成Windows服务会比较方便，我直接添加了相关配置文件，具体配置信息可以[看这里](https://www.npmjs.com/package/node-windows)，希望可以帮到你

2021-08-31 16:30 UTC, pan93412 requested changes
此外建議在 README.md 裡面加入相應說明，會比較方便用戶操作。

2021-08-31 16:30 UTC, pan93412 commented on package-lock.json
> +{
我們是用 `yarn` 不是 `npm`，為保持統一性，用 `yarn install` 更新 `yarn.lock` 會比較好。

2021-08-31 16:44 UTC, pan93412 commented on package-lock.json
> +{
```sh
npm install -g yarn && rm package-lock.json && yarn
```

2021-08-31 17:48 UTC, whosydd commented on package-lock.json
> +{
抱歉，习惯用npm了，已改

2021-08-31 22:57 UTC, merged

2021-08-31 22:58 UTC, pan93412 commented
感謝貢獻～ :)

2021-11-04 13:28 UTC, SekiBetu commented
https://github.com/winsw/winsw 这个也可以啊

2021-11-04 13:32 UTC, SekiBetu commented
https://github.com/winsw/winsw 这个也可以啊，不用让用户安装nodejs
写一个.bat文件，双击就行了

```
winsw install
winsw start
```

一个示例的配置文件
```xml
<service>
  <id>UnblockNeteaseMusic</id>
  <name>解锁网易云音乐客户端变灰歌曲</name>
  <description>解锁网易云音乐客户端变灰歌曲</description>
  <executable>UnblockNeteaseMusic.exe</executable>
  <arguments>-p 11111</arguments>
  <logmode>rotate</logmode>
  <logpath>log</logpath>
  <priority>Normal</priority>
  <startmode>Automatic</startmode>
  <delayedAutoStart>true</delayedAutoStart>
  <onfailure action="restart" delay="60 sec"/>
  <onfailure action="restart" delay="120 sec"/>
</service>
```

2021-11-05 04:48 UTC, whosydd commented
@SekiBetu 这个有点意思，不过话说项目运行不是也得依靠node嘛。。。

2021-11-05 04:49 UTC, SekiBetu commented
> @SekiBetu 这个有点意思，不过话说项目运行不是也得依靠node嘛。。。

编译的时候nodejs已经整合进去了啊，但是你这个node指令是单独的，需要用户安装nodejs

2021-11-05 04:51 UTC, pan93412 commented
> > @SekiBetu 这个有点意思，不过话说项目运行不是也得依靠node嘛。。。
> 
> 编译的时候nodejs已经整合进去了啊，不然release为什么那么大，还是个.exe程序，但是你这个node指令是单独的，需要用户安装nodejs

或者是關注隔壁新的 [server-rust](https://github.com/UnblockNeteaseMusic/server-rust) 專案。[目前在積極重構與開發](https://github.com/UnblockNeteaseMusic/server-rust/tree/feat/full-server)，亦歡迎有興趣的朋友一起貢獻～

2021-11-05 04:54 UTC, SekiBetu commented
> > > @SekiBetu 这个有点意思，不过话说项目运行不是也得依靠node嘛。。。
> > 
> > 
> > 编译的时候nodejs已经整合进去了啊，不然release为什么那么大，还是个.exe程序，但是你这个node指令是单独的，需要用户安装nodejs
> 
> 或者是關注隔壁新的 [server-rust](https://github.com/UnblockNeteaseMusic/server-rust) 專案。[目前在積極重構與開發](https://github.com/UnblockNeteaseMusic/server-rust/tree/feat/full-server?rgh-link-date=2021-11-05T04%3A51%3A52Z)，亦歡迎有興趣的朋友一起貢獻～

感觉golang更加适合开发这种流量代理的工具，rust最后编译完的体积有点大

2021-11-05 04:56 UTC, pan93412 commented
```
➜  debug git:(feat/full-server) ✗ du -sh unm_cli
 18M	unm_cli
```

還好吧？

2021-11-05 04:58 UTC, SekiBetu commented
> ```
> ➜  debug git:(feat/full-server) ✗ du -sh unm_cli
>  18M	unm_cli
> ```
> 
> 還好吧？更何況這個是 debug 版，還沒有優化。

https://github.com/cnsilvan/UnblockNeteaseMusic 这边还有一个我之前看到的golang项目，开发者可以互相交流下

2021-11-05 05:00 UTC, pan93412 commented
> > ```
> > ➜  debug git:(feat/full-server) ✗ du -sh unm_cli
> >  18M	unm_cli
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 還好吧？更何況這個是 debug 版，還沒有優化。
> 
> 
> https://github.com/cnsilvan/UnblockNeteaseMusic 这边还有一个我之前看到的golang项目，开发者可以互相交流下

我有注意到這個專案。然而他似乎沒有給除了 email 之外的聯絡方式？之後我有空再跟他聯絡。

2021-11-05 05:00 UTC, pan93412 commented
> ```
> ➜  debug git:(feat/full-server) ✗ du -sh unm_cli
>  18M	unm_cli
> ```
> 
> 
>      
>   
> 
> 還好吧？更何況這個是 debug 版，還沒有優化。

```
➜  unm-server-rust git:(feat/full-server) ✗ du -sh ./target/release/unm_cli 
3.4M	./target/release/unm_cli
```

優化過的大小。