add weighting system for single song source
1715173329/UnblockNeteaseMusic pull request #171
Opened 2021-09-19 07:19 UTC by 1582421598

2021-09-19 07:22 UTC, 1582421598 commented
多个音源之间的权重系统在目前的情况下，可能需要大改一下match.js和各个音源的format。

2021-09-19 07:37 UTC, pan93412 requested changes

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	const similarityVaule = similarity.compareTwoStrings(songName, info.name)
這裡拼字有誤。是 `Value`。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +const calcWeight = (song, info) => {
我這裡建議比照我們的新 code 加上 JSDoc。不加也沒關係啦w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +const replaceSpace = (string) => string.replace(/&nbsp;/g, ' ').replace(/nbsp;/g, ' ')
我這裡建議比照我們的新 code 加上 JSDoc。不加也沒關係啦w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	var weight = 0
雖然這裡 `var` 跟 `let` 的 scope 相似，但我覺得這裡用 `let` 會比較棒。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +		var authorName = ''
雖然這裡 `var` 跟 `let` 的 scope 相似，但我覺得這裡用 `let` 會比較棒。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +				authorName = authorName + artists.name.replace(/&nbsp;/g, ' ')
可以簡化成 `+=`。此外你這裡要不要直接使用上面的 `replaceSpace()`

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +		authorName = replaceSpace(authorName).toLowerCase()
根據上面的 code，當心重複 `replaceSpace()`。如果可以的話，要不要把上面取代 nbsp 的作業移到這裡？

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +			if (authorName.includes(originalName)) weight = weight + 0.1
`+=` 會更好w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +			else if (songName.includes(originalName)) weight = weight + 0.1
`+=` 會更好w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +			else weight = weight - 0.1
`-=` 會更好w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +const selectList = (list, info) => {
我這裡建議比照我們的新 code 加上 JSDoc。不加也沒關係啦w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	var result = list[0];
雖然這裡 `var` 跟 `let` 的 scope 相似，但我覺得這裡用 `let` 會比較棒。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	var lastweighting = 0;
1. 雖然這裡 `var` 跟 `let` 的 scope 相似，但我覺得這裡用 `let` 會比較棒。
2. `lastWeighting` 會不會比較好看一點（要改的話，用 IDE/VS Code 內建的 Refactor 功能！）

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	for (let index = 0; index < list.length; index++) {
看起來沒有需要 `index` 的場景。可以直接 `for (let entry of list)` 會比較好看。

此外你有興趣的話，也可以參考一下 `.reduce` 之類更簡化的方法。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	var weighting = 0;
雖然這裡 `var` 跟 `let` 的 scope 相似，但我覺得這裡用 `let` 會比較棒。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +const selectArray = array => {
我這裡建議比照我們的新 code 加上 JSDoc。不加也沒關係啦w

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	var song = array[0]
雖然這裡 var 跟 let 的 scope 相似，但我覺得這裡用 let 會比較棒。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
> +	for (let index = 1; index < array.length; index++) {
看起來沒有需要 index 的場景。可以直接 `for (let entry of list)` 會比較好看。

此外你有興趣的話，也可以參考一下 `.map` 之類的方法（不過沒有必要 refactor 成這種方式）。

2021-09-19 07:37 UTC, pan93412 commented on src/provider/select.js
>  module.exports = (list, info) => {
我這裡建議比照我們的新 code 加上 JSDoc。不加也沒關係啦w

2021-09-19 07:37 UTC, pan93412 commented on src/similarity.js
> +const compareTwoStrings = (first, second) => {
我這裡建議比照我們的新 code 加上 JSDoc。不加也沒關係啦w

```js
/**
 * @param {string} first
 * @param {string} second
 * @returns {number}
 */
```

2021-09-19 07:37 UTC, pan93412 commented on src/similarity.js
> +	if (!areArgsValid(mainString, targetStrings)) throw new Error('Bad arguments: First argument should be a string, second should be an array of strings');
建議自己寫一個 Error class，不太建議直接引 `Error`

2021-09-19 07:37 UTC, pan93412 commented on src/similarity.js
> +const areArgsValid = (mainString, targetStrings) => {
#JSDoc

2021-09-19 07:37 UTC, pan93412 commented on src/similarity.js
> +	return true;
或許可以用 `&&` 減少 `return false;` 的量

2021-09-19 07:38 UTC, pan93412 commented
抱歉我問題一堆，但我真的非常感謝你的幫忙！ ❤️

2021-09-19 07:41 UTC, pan93412 commented
resolved https://github.com/UnblockNeteaseMusic/server/issues/137#issuecomment-915993287

2021-09-19 07:41 UTC, 1582421598 commented
> 抱歉我問題一堆，但我真的非常感謝你的幫忙！ ❤️

非常棒的问题呢，我也是为了改这个项目才上手的nodejs，代码方面还是不太了解它的一些特性。

2021-09-19 07:41 UTC, pan93412 commented
resolved https://github.com/UnblockNeteaseMusic/server/issues/137#issuecomment-915993287

fyi @SpeedPartners

2021-09-19 07:47 UTC, 1582421598 commented on src/provider/select.js
> +		authorName = replaceSpace(authorName).toLowerCase()
有多个作者的情况下不太方便弄到这里。

2021-09-19 07:48 UTC, pan93412 commented
> 多个音源之间的权重系统在目前的情况下，可能需要大改一下match.js和各个音源的format。

嗯？不太懂意思。大部分音源應該都已經格式化過了；一部分音源（如 youtube 系列）你可以幫我開個 Issue 追蹤一下

<img width="646" alt="截圖 2021-09-19 下午3 44 43" src="https://user-images.githubusercontent.com/28441561/133919620-5878a9dc-f8f8-409c-8ef4-a58fa37ffeae.png">

<img width="1135" alt="截圖 2021-09-19 下午3 46 58" src="https://user-images.githubusercontent.com/28441561/133919667-d8471c96-b2d3-409a-96bd-92bffeb71154.png">

2021-09-19 07:49 UTC, pan93412 commented on src/provider/select.js
> +		authorName = replaceSpace(authorName).toLowerCase()
了解

2021-09-19 07:53 UTC, 1582421598 commented
> > 多个音源之间的权重系统在目前的情况下，可能需要大改一下match.js和各个音源的format。
> 
> 嗯？不太懂意思。大部分音源應該都已經格式化過了，而且沒 match 的會直接 `Promise.reject()`；一部分音源（如 youtube 系列）你可以幫我開個 Issue 追蹤一下
> 
> <img alt="截圖 2021-09-19 下午3 44 43" width="646" src="https://user-images.githubusercontent.com/28441561/133919620-5878a9dc-f8f8-409c-8ef4-a58fa37ffeae.png">
> 
> <img alt="截圖 2021-09-19 下午3 46 58" width="1135" src="https://user-images.githubusercontent.com/28441561/133919667-d8471c96-b2d3-409a-96bd-92bffeb71154.png">

这个权重系统是在多音源中进行选择的，首先在单个音源里选出权重最高的一个，之后在多个音源里选择出权重最高的一个，然后为了加到这个项目里，删去了多音源的选择部分(毕竟之前用的Promise.all)qwq

2021-09-19 08:01 UTC, pan93412 commented
> > > 多个音源之间的权重系统在目前的情况下，可能需要大改一下match.js和各个音源的format。
> > 
> > 
> > 嗯？不太懂意思。大部分音源應該都已經格式化過了，而且沒 match 的會直接 `Promise.reject()`；一部分音源（如 youtube 系列）你可以幫我開個 Issue 追蹤一下
> > <img alt="截圖 2021-09-19 下午3 44 43" width="646" src="https://user-images.githubusercontent.com/28441561/133919620-5878a9dc-f8f8-409c-8ef4-a58fa37ffeae.png">
> > <img alt="截圖 2021-09-19 下午3 46 58" width="1135" src="https://user-images.githubusercontent.com/28441561/133919667-d8471c96-b2d3-409a-96bd-92bffeb71154.png">
> 
> 这个权重系统是在多音源中进行选择的，首先在单个音源里选出权重最高的一个，之后在多个音源里选择出权重最高的一个，然后为了加到这个项目里，删去了多音源的选择部分(毕竟之前用的Promise.all)qwq

不然你改成 `Promise.allSettled()` 然後寫 `Promise.all()` 時的邏輯？我再看看要怎麼整合 all 和 any。

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

2021-09-19 08:04 UTC, 1582421598 commented
> > > > 多个音源之间的权重系统在目前的情况下，可能需要大改一下match.js和各个音源的format。
> > > 
> > > 
> > > 嗯？不太懂意思。大部分音源應該都已經格式化過了，而且沒 match 的會直接 `Promise.reject()`；一部分音源（如 youtube 系列）你可以幫我開個 Issue 追蹤一下
> > > <img alt="截圖 2021-09-19 下午3 44 43" width="646" src="https://user-images.githubusercontent.com/28441561/133919620-5878a9dc-f8f8-409c-8ef4-a58fa37ffeae.png">
> > > <img alt="截圖 2021-09-19 下午3 46 58" width="1135" src="https://user-images.githubusercontent.com/28441561/133919667-d8471c96-b2d3-409a-96bd-92bffeb71154.png">
> > 
> > 
> > 这个权重系统是在多音源中进行选择的，首先在单个音源里选出权重最高的一个，之后在多个音源里选择出权重最高的一个，然后为了加到这个项目里，删去了多音源的选择部分(毕竟之前用的Promise.all)qwq
> 
> 不然你改成 `Promise.allSettled()` 然後寫 `Promise.all()` 時的邏輯？我再看看要怎麼整合 all 和 any。
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

行，我去改改

2021-09-19 09:57 UTC, 1582421598 commented
> > > > 多个音源之间的权重系统在目前的情况下，可能需要大改一下match.js和各个音源的format。
> > > 
> > > 
> > > 嗯？不太懂意思。大部分音源應該都已經格式化過了，而且沒 match 的會直接 `Promise.reject()`；一部分音源（如 youtube 系列）你可以幫我開個 Issue 追蹤一下
> > > <img alt="截圖 2021-09-19 下午3 44 43" width="646" src="https://user-images.githubusercontent.com/28441561/133919620-5878a9dc-f8f8-409c-8ef4-a58fa37ffeae.png">
> > > <img alt="截圖 2021-09-19 下午3 46 58" width="1135" src="https://user-images.githubusercontent.com/28441561/133919667-d8471c96-b2d3-409a-96bd-92bffeb71154.png">
> > 
> > 
> > 这个权重系统是在多音源中进行选择的，首先在单个音源里选出权重最高的一个，之后在多个音源里选择出权重最高的一个，然后为了加到这个项目里，删去了多音源的选择部分(毕竟之前用的Promise.all)qwq
> 
> 不然你改成 `Promise.allSettled()` 然後寫 `Promise.all()` 時的邏輯？我再看看要怎麼整合 all 和 any。
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

基本能用了，不过有一些我不太了解的报错点。
`ERROR: (provider/match) Cannot read properties of null (reading 'includes')
    TypeError: Cannot read properties of null (reading 'includes')
        at isHost (D:\GithubProjects\server\src\utilities.js:12:13)
        at D:\GithubProjects\server\src\utilities.js:22:42
        at D:\GithubProjects\server\src\provider\match.js:120:7
        at Map.forEach (<anonymous>)
        at check (D:\GithubProjects\server\src\provider\match.js:118:16)
        at getAudioFromSource (D:\GithubProjects\server\src\provider\match.js:48:21)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)`

2021-09-19 10:37 UTC, pan93412 commented
我先看看怎麼改會比較合適。

2021-09-20 06:41 UTC, pan93412 commented
Note: 我這裡在重構這套系統。請暫時先不合併本 PR。

2024-02-04 09:42 UTC, closed without merging