新增歌曲源json文件和匹配方法
1715173329/UnblockNeteaseMusic pull request #660
Opened 2022-04-29 08:09 UTC by zmqcherish

1. 使用音源文件music.json解决音源匹配错误问题，可指定对应歌曲的url或对应音源的正确id
2. 更改select中方法，将匹配专辑名作为前置匹配条件，如未命中再匹配歌曲长度

2022-04-29 12:27 UTC, pan93412 requested changes

2022-04-29 12:27 UTC, pan93412 commented on src/provider/match.js
> +
同 kugou, kuwo 問題。

2022-04-29 12:27 UTC, pan93412 commented on src/provider/select.js
> +				s.album?.name && s.album.name == album.name
`s.album?.name === album.name` 這樣就好。如果前者是 undefined，同樣會導致整個 expression 變 `false`。

2022-04-29 12:27 UTC, pan93412 commented on src/utilities.js
> +var filePath = path.join(__dirname, '.', 'music.json');
用 `const`

2022-04-29 12:27 UTC, pan93412 commented on src/utilities.js
> +var musicDataRaw = '{}';
用 `let`

2022-04-29 12:27 UTC, pan93412 commented on src/utilities.js
> +
建議寫 `logger.info` 讓使用者知情。

2022-04-29 12:27 UTC, pan93412 commented on src/utilities.js
> +	musicDataRaw = fs.readFileSync(filePath);
建議寫成 async 函數，然後用 `await fs.promises.readFile`

2022-04-29 12:27 UTC, pan93412 commented on src/utilities.js
> +const musicMatchData = JSON.parse(musicDataRaw);
這裡有可能會 exception。建議同上，製作 fallback 機制。這裡的 logging 宜用 `warn`。

2022-04-29 17:20 UTC, zmqcherish commented
@pan93412 非常感谢耐心code review，给出的建议我争取改正。因为是后端开发写的node代码不是很规范，给你造成麻烦了。

2022-04-29 23:59 UTC, pan93412 commented
> @pan93412 非常感谢耐心code review，给出的建议我争取改正。因为是后端开发写的node代码不是很规范，给你造成麻烦了。

太客氣了啦。也很感激你的貢獻 ❤️

2022-04-30 07:07 UTC, zmqcherish commented
重新push了更改后的code，依然存在不规范除，请指正。

2022-05-10 08:45 UTC, pan93412 commented
先 rebase & 修正一些 issue。裡面有一些邏輯是需要改進的，這部分我有空再來處理。

2022-05-10 09:34 UTC, pan93412 commented
@zmqcherish 你再幫我看一下 refactor 有什麼問題。謝謝啦～

2022-08-13 11:36 UTC, 1715173329 commented
Ping @zmqcherish

2023-07-10 18:44 UTC, closed without merging